server:
  port: 0

jwt:
  secret: dasdasdsadasdsadad

spring:
  application:
    name: ms-products

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: ${EUREKA_URI:http://localhost:8761/eureka}