jwt:
  secret: dasdasdsadasdsadad

server:
  port: 8189

spring:
  application:
    name: ms-auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: ${EUREKA_URI:http://localhost:8761/eureka}

